spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb1?serverTimezone=UTC
    username: root
    password: Synopsis2019   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false         
         